### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by arran4** [imandolatkia/Android-Animated-Theme-Manager#1]
I got an email:

> Hello and greetings.
>
>I hope you are doing well.
>
>I visited your GitHub profile and I understood you are interested in Android.
>
>Recently I published a library on GitHub which creates custom themes and changes them dynamically with ripple animation.
>
>I will be grateful if you review it and send me your precious opinions and pull requests as a contributor.
>
>Here is my library link: https://github.com/imandolatkia/Android-Animated-Theme-Manager
>
 >
>
>Also if you work with android linter and have problems with baselines for build variants, please check my document here: >https://github.com/imandolatkia/Android-buildvariants-baselines-for-linter
>
> 
>
>Thanks for your care and support
>
>Best Regards,
>
> Iman Dolatkia, Senior Android Developer @ Taaghche e-books

I feel that this is poorly targeted as I forked a repo once, and it's probably archived. Please update your engine so I don't get any more emails to do with android.

**Comment by ankit1057** [comment]
Hey, this library is a pretty cool and efficient system, we shall help develop it further. Isn't that the whole point of open-source? We all help each other out and create amazing stuff doing so?

**Comment by arran4** [comment]
@ankit1057 I received this as an email via hubspot. -- I am not an android developer.. Which means I'm contributing by helping improve the marketing algorithm by suggesting it might be too broad which would also save the project money.

**Comment by imandolatkia** [comment]
Dear @ankit1057 
Sorry I took your time and send the wrong email to you.
But I saw that you gave stars to more than 10 android repositories and I guessed that you are interested in android.
Despite this, I am happy to talk with you.

**Comment by imandolatkia** [comment]
Dear @ankit1057, 
I'm so happy that you liked my repo.
Please feel free to send me any comments and pull requests.
