### ISSUE TITLE
Cannot start anim on deAttachedView

### ISSUE THREAD

**Issue by RohitVermaOP** [imandolatkia/Android-Animated-Theme-Manager#11]
```
java.lang.IllegalStateException: Cannot start this animator on a detached view!
```
When i click change theme button, all working good but when i open any acivity and go back then click, and crashed

**Comment by imandolatkia** [comment]
@RohitVermaOP 
Hi,
I added the multi Activities sample and fix the bug.
please use version 1.1.4:

```gradle
dependencies {
    implementation "com.dolatkia:animated-theme-manager:1.1.4"
}
```
Thank you for your report.
