### ISSUE TITLE
save the theme

### ISSUE THREAD

**Issue by KursatAktunc** [imandolatkia/Android-Animated-Theme-Manager#18]
I don't understand what needs to be done to save the theme next time. How can we record in onDestroy. Can you show me a preview?

**Comment by imandolatkia** [comment]
Hi @KursatAktunc,
For example, if a user closes the application with the night theme, it's better to open the application at night theme next time again.
To do this, you can save the current them id in preferences when the application is closing (onDestroy) and fetch that id from preferences when the application starts again and pass the corresponding theme in getStartTheme() method.

please check this for preferences: https://developer.android.com/training/data-storage/shared-preferences

```
// save current them id in preferences 
    override fun onDestroy() {
        super.onDestroy()
        // save getThemeManager().getCurrentTheme()?.id() in prefs
        // check: https://developer.android.com/training/data-storage/shared-preferences
    }

// get start theme
    override fun getStartTheme(): AppTheme {
        val savedThemId = // fetch saved theme id from preferences 
        return when(savedThemId){
            LightTheme.ThemeId -> LightTheme()
            NightTheme.ThemeId -> NightTheme()
            PinkTheme.ThemeId -> PinkTheme()
            else -> LightTheme()
        }
    }
```
