### ISSUE TITLE
RecyclerView

### ISSUE THREAD

**Issue by SudoDios** [imandolatkia/Android-Animated-Theme-Manager#8]
how to update RecyclerView?

**Comment by imandolatkia** [comment]
HI @SudoDios,
It's a really good question.

1- You should synchronize the RecyclerView theme in Viewholders. I mean in the RecyclerView adapter and in```onBindViewHolder``` method, with the use of ```ThemeManager```.
2- After the theme is changed, if the fragment that contained RecyclerView was displaying, call ```notifyDataSetChanged()``` from its adapter.

I will add the sample in a week.

**Comment by SudoDios** [comment]
Thankful.  
I solved this issue that day but I forgot to close this issue 😌

**Comment by FaArIsH** [comment]
@SudoDios can you share sample?

**Comment by Ufransa** [comment]
> @SudoDios can you share sample?

Hi @FaArIsH ! Di you manage to solve it? I´m also triying to do the same with the action bar if you can help me. Thanks !!

**Comment by SudoDios** [comment]
You can solve the problem with the help of observer in everywhere

**Comment by Ufransa** [comment]
Can you elaborate that a bit more @SudoDios? Thanks !

**Comment by SudoDios** [comment]
What should I explain?  🧐
This is very easy

**Comment by FaArIsH** [comment]
i modified my adapter by looking at this code https://github.com/karimov0147/E-Book-Little-Prince/blob/master/app/src/main/java/com/example/bubook/utills/AdapterRV.kt 
and now i m able to call adapter.notifyDataSetChanged()
