### ISSUE TITLE
Cannot start this animator on a detached view!

### ISSUE THREAD

**Issue by SudoDios** [imandolatkia/Android-Animated-Theme-Manager#9]
How to destroy finished activity theme manager ?????

**Comment by imandolatkia** [comment]
Hi @SudoDios
If you mean ```ThemeActivity```, it's a simple AppCompatActivity. You can work with it like AppCompatActivity.
If you mean ```ThemeManager```, it's a singleton and doesn't need to be destroyed. the application always needs it. Every time that Fragment/Activity changes, we use it to synchronize the theme. It's not only for change theme animation.
If you don't agree, please tell me in more detail.
Thank you :)

**Comment by SudoDios** [comment]
Please wait while I send the code sample

**Comment by SudoDios** [comment]
Can you give an example code of how many activities?

**Comment by imandolatkia** [comment]
Ok, I will add it on this week.

**Comment by SudoDios** [comment]
Thanks 🙏

**Comment by RohitVermaOP** [comment]
Same happened with me

**Comment by imandolatkia** [comment]
@SudoDios 
Hi,
I added the multi Activities sample and fix the bug.
please use version 1.1.4:

```gradle
dependencies {
    implementation "com.dolatkia:animated-theme-manager:1.1.4"
}
```
Thank you for your report.

**Comment by SudoDios** [comment]
Thankful.
